version: "3.3"
services: 
  aws-localstack:
    container_name: aws-localstack 
    image: localstack/localstack 
    restart: always 
    network_mode: bridge 
    ports:
      - "127.0.0.1:4510-4559:4510-4559"
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:5678:5678"
    environment:
      - AWS_DEFAULT_REGION=sa-east-1
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=admin
      - DEFAULT_REGION=sa-east-1
      - SERVICES=s3, dynamodb, apigateway, cloudformation, cloudwatch, iam, lambda, route53, ses, sns, sqs, stepfuncstions
      - DEBUG=${DEBUG-}
      - DATA_DIR=${DATA_DIR-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-docker}
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DISABLE_CORS_CHECKS=1 
      - LAMBDA_REMOTE_DOCKER=false
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"